{{ with .Values.cardanoNewsApi }}
{{ if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: cardano-news-api
  labels:
    app: cardano-news-api
spec:
  selector:
    app: cardano-news-api
  ports:
    - protocol: TCP
      name: api
      port: 80
      targetPort: api
{{ end }}
{{ end }}
