{{ with .Values.crawler }}
{{ if and .enabled .monitoringEnabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cf-ledger-crawler
  labels:
    release: prometheus-stack
spec:
  endpoints:
    - path: /actuator/prometheus
      port: api
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      app: cf-ledger-crawler
{{ end }}
{{ end }}