{{ with .Values.crawler }}
{{ if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-ledger-crawler
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: cf-ledger-crawler
  template:
    metadata:
      labels:
        app: cf-ledger-crawler
    spec:
      containers:
        - name: cf-ledger-crawler
          image: "{{ .image.repository }}:{{ .image.tag }}"
#          command: ["bash", "-c", "sleep 999999"]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .springProfiles }}

            - name: PORT
              value: {{ .port | quote }}
            - name: BOOTSTRAP_SERVER
              value: {{ .kafka.bootstrapServer }}

#            - name: REDIS_MASTER_NAME
#              value: {{ .redis.master.name }}
#            - name: REDIS_SENTINEL_HOST
#              value: {{ .redis.sentinel.host }}
#            - name: REDIS_SENTINEL_PASS
#              valueFrom:
#                secretKeyRef:
#                  name: {{ .redis.secretName }}
#                  key: redis-password

            - name: REDIS_CLUSTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secretName }}
                  key: redis-password
            - name: NODE_ADDRESSES
              value: {{ .redis.cluster.hosts }}

            - name: CRAWLER_NAME
              value: {{ .crawler.name }}
            - name: BLOCKS_TOPIC
              value: {{ .crawler.blocks.topic }}
            - name: BLOCKS_ROLLBACK_TOPIC
              value: {{ .crawler.blocks.rollbackTopic }}

            - name: NODE_ADDRESS
              value: {{ .cardano.node.address }}
            - name: NODE_PORT
              value: {{ .cardano.node.port | quote }}
            - name: NETWORK_MAGIC
              value: {{ .cardano.node.networkMagic | quote }}

          ports:
            - name: api
              containerPort: {{ .port }}

      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 2
{{ end }}
{{ end }}
