{{ with .Values.explorerAuthentication }}
{{ if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-explorer-authentication
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: cf-explorer-authentication
  template:
    metadata:
      labels:
        app: cf-explorer-authentication
    spec:
      containers:
        - name: cf-explorer-authentication
          image: "{{ .image.repository }}:{{ .image.tag }}"
#          command: ["bash", "-c", "sleep 999999"]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .springProfiles }}

            - name: EXPLORER_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.hostKey }}
            - name: EXPLORER_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.portKey }}
            - name: EXPLORER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.userKey }}
            - name: EXPLORER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.passwordKey }}
            - name: EXPLORER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.dbKey }}
            - name: EXPLORER_DB_SCHEMA
              value: {{ .postgres.schema }}

            - name: FLYWAY_ENABLED
              value: {{ .flywayEnabled | quote }}
            - name: SWAGGER_CLIENT_URL
              value: {{ tpl .swaggerClientUrl $ }}
            - name: SWAGGER_SERVER_URL
              value: {{ .swaggerServerUrl }}
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .region.secret.name }}
                  key: {{ .region.secret.key }}
            - name: SES_EMAIL_FROM
              value: {{ .emailFrom }}
            - name: SES_EMAIL_FROM_NAME
              value: {{ .emailFromName }}
            - name: SES_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: SES_ACCESS_KEY_ID
            - name: SES_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: SES_SECRET_ACCESS_KEY

            - name: KEYCLOAK_REALM_NAME
              value: {{ .keycloakRealmName | default "cardano_explorer" | quote }}
            - name: KEYCLOAK_SERVER_URL
              value: {{ .keycloakServerUrl | default "http://keycloak:8080" | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .keycloakClientId | default "cardano_authentication_client" | quote }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: KEYCLOAK_CLIENT_SECRET
            - name: RSA_PUBLIC_KEY_AUTH
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: RSA_PUBLIC_KEY_AUTH
            - name: RSA_PUBLIC_KEY_MAIL
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: RSA_PUBLIC_KEY_MAIL
            - name: RSA_PRIVATE_KEY_MAIL
              valueFrom:
                secretKeyRef:
                  name: infra-secrets
                  key: RSA_PRIVATE_KEY_MAIL

          ports:
            - name: api
              containerPort: {{ .port }}
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 2
{{ end }}
{{ end }}
