{{ with .Values.explorerAuthentication }}
{{ if .enabled }}
  {{- range $v := $.Values.ingressDomains }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cf-explorer-authentication-{{ $v.name }}"
spec:
  rules:
    {{- if eq $.Values.network "mainnet" }}
    - host: "auth-api.{{ $v.domain }}"
    {{- else }}
    - host: "auth-api.{{ $.Values.network }}.{{ $v.domain }}"
    {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-authentication
                port:
                  number: {{ .port }}
  tls:
    - hosts:
        {{- if eq $.Values.network "mainnet" }}
        - "auth-api.{{ $v.domain }}"
        {{- else }}
        - "auth-api.{{ $.Values.network }}.{{ $v.domain }}"
        {{- end }}
  {{- end }}
{{ end }}
{{ end }}
