{{ with .Values.explorerApi }}
{{ if .enabled }}
{{- $root := . -}}
  {{- range $v := $.Values.ingressDomains }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cf-explorer-api-{{ $v.name }}"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-api-cache-header-rewrite@kubernetescrd
spec:
  rules:
    - host: "api.{{ $v.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-api
                port:
                  number: {{ $root.port }}
  tls:
    - hosts:
        - "api.{{ $v.domain }}"
  {{- end }}
{{ end }}
{{ end }}
