{{ with .Values.explorerAuthentication }}
{{ if .enabled }}
{{- $root := . -}}
  {{- range $v := $.Values.ingressDomains }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cf-explorer-authentication-{{ $v.name }}"
spec:
  rules:
    - host: "auth-api.{{ $v.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-authentication
                port:
                  number: {{ $root.port }}
  tls:
    - hosts:
        - "auth-api.{{ $v.domain }}"
  {{- end }}
{{ end }}
{{ end }}
