{{ with .Values.explorerAuthentication }}
{{ if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: cf-explorer-authentication
  labels:
    app: cf-explorer-authentication
spec:
  selector:
    app: cf-explorer-authentication
  ports:
    - protocol: TCP
      name: api
      port: {{ .port }}
      targetPort: api
      {{- with .service.nodePort }}
      nodePort: {{ . }}
      {{- end}}
  type: {{ .service.type | default "ClusterIP" }}
{{ end }}
{{ end }}
