{{ with .Values.explorerAuthentication }}
{{ if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cf-explorer-authentication
spec:
  rules:
    - host: auth-api.{{ $.Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-authentication
                port:
                  number: {{ .port }}
  tls:
    - hosts:
        - api.{{ $.Values.domain }}
{{ end }}
{{ end }}
