{{ with .Values.explorerApi }}
{{ if .enabled }}
{{- $root := . -}}
  {{- range $v := $.Values.ingressDomains }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cf-explorer-api-{{ $v.name }}"
spec:
  rules:
    {{- if eq $.Values.network "mainnet" }}
    - host: "api.{{ $v.domain }}"
    {{- else }}
    - host: "api.{{ $.Values.network }}.{{ $v.domain }}"
    {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-api
                port:
                  number: {{ $root.port }}
  tls:
    - hosts:
        {{- if eq $.Values.network "mainnet" }}
        - "api.{{ $v.domain }}"
        {{- else }}
        - "api.{{ $.Values.network }}.{{ $v.domain }}"
        {{- end }}
  {{- end }}
{{ end }}
{{ end }}
