{{ with .Values.explorerRewardsApi }}
{{ if .enabled }}
{{- $root := . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rewards-api-custom-headers
  namespace: kube-system
spec:
  headers:
    customResponseHeaders:
      Cross-Origin-Opener-Policy: "same-origin"
  {{- range $v := $.Values.ingressDomains }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cf-explorer-rewards-api-{{ $v.name }}"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-rewards-api-custom-headers@kubernetescrd
spec:
  rules:
    - host: "rewards-api.{{ $v.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-rewards-api
                port:
                  number: 80
  tls:
    - hosts:
        - "rewards-api.{{ $v.domain }}"
  {{- end }}
{{ end }}
{{ end }}
