{{ with .Values.explorerFrontEnd }}
{{ if .enabled }}
{{- $root := . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: api-cache-header-rewrite
  namespace: kube-system
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "max-age=30, must-revalidate"
  {{- range $v := $.Values.ingressDomains }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "cf-explorer-fe-{{ $v.name }}"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-api-cache-header-rewrite@kubernetescrd
spec:
  rules:
    - host: "{{ $v.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-fe
                port:
                  number: {{ $root.port }}
  tls:
    - hosts:
        - "{{ $v.domain }}"
  {{- end }}
{{ end }}
{{ end }}
