{{ with .Values.explorerApi }}
{{ if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-explorer-api
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: cf-explorer-api
  template:
    metadata:
      labels:
        app: cf-explorer-api
    spec:
      containers:
        - name: cf-explorer-api
          image: "{{ .image.repository }}:{{ .image.tag }}"
#          command: ["bash", "-c", "sleep 999999"]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .springProfiles }}
            - name: HOST
              value: {{ .postgres.host }}
            - name: PORT_DB
              value: {{ .postgres.port | quote }}
            - name: USERNAME_DB
              value: {{ .postgres.user }}
            - name: PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.key }}
            - name: DB
              value: {{ .postgres.dbName }}
            - name: SCHEMA
              value: {{ .postgres.schema }}

            {{- if eq .redis.mode "sentinel" }}
            - name: REDIS_MASTER_NAME
              value: {{ .redis.master.name }}
            - name: REDIS_SENTINEL_HOST
              value: {{ .redis.sentinel.host }}
            - name: REDIS_SENTINEL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: {{ .redis.secret.key }}
            {{- else if eq .redis.mode "cluster" }}
            - name: REDIS_CLUSTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: {{ .redis.secret.key }}
            - name: NODE_ADDRESSES
              value: {{ .redis.cluster.hosts }}
            {{- else }}
            - name: REDIS_STANDALONE_HOST
              value: {{ .redis.standalone.host }}
            - name: REDIS_STANDALONE_PORT
              value: {{ .redis.standalone.port | quote }}
            - name: REDIS_STANDALONE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: {{ .redis.secret.key }}
            {{- end }}
            - name: S3_BUCKET_NAME
              value: {{ .s3.bucketName }}
            - name: S3_REGION
              value: {{ .s3.region }}
            - name: S3_ENDPOINT
              value: {{ .s3.endpoint }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .s3.secret.name }}
                  key: {{ .s3.secret.accessKeyKey }}
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .s3.secret.name }}
                  key: {{ .s3.secret.secretKeyKey }}

          ports:
            - name: api
              containerPort: {{ .port }}

      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 2
{{ end }}
{{ end }}
