{{ with .Values.explorerApi }}
{{ if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-explorer-api
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: cf-explorer-api
  template:
    metadata:
      labels:
        app: cf-explorer-api
    spec:
      containers:
        - name: cf-explorer-api
          image: "{{ .image.repository }}:{{ .image.tag }}"
#          command: ["bash", "-c", "sleep 999999"]
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .springProfiles }}

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.hostKey }}
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.portKey }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.userKey }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.passwordKey }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .postgres.secret.name }}
                  key: {{ .postgres.secret.dbKey }}
            - name: DB_SCHEMA
              value: {{ .postgres.schema }}

            - name: API_CHECK_REWARD_URL
              value: "{{ .explorerRewardsUrl }}/api/v1/rewards/fetch"
            - name: API_CHECK_POOL_HISTORY_URL
              value: "{{ .explorerRewardsUrl }}/api/v1/pool-history/fetch"
            - name: API_CHECK_POOL_INFO_URL
              value: "{{ .explorerRewardsUrl }}/api/v1/pool-info/fetch"
            - name: API_CHECK_EPOCH_STAKE_URL
              value: "{{ .explorerRewardsUrl }}/api/v1/epoch-stake/fetch"
            - name: API_CHECK_ADA_POTS_URL
              value: "{{ .explorerRewardsUrl }}/api/v1/ada-pots/fetch"
            - name: API_CHECK_EPOCH_URL
              value: "{{ .explorerRewardsUrl }}/api/v1/epochs/fetch"

            - name: API_NEWS_URL
              value: "http://cardano-news-api?limit=%d&offset=%d"
            - name: API_NEWS_CACHE_TIME
              value: "120"

            - name: API_MARKET_URL
              value: "https://api.coingecko.com/api/v3/coins/markets?ids=cardano&vs_currency=%s"
            - name: API_MARKET_CACHE_TIME
              value: "120"
            - name: REPORT_LIMIT_PER_24HOURS
              value: "2"
            - name: EPOCH_DAYS
              value: "5"

            {{- if eq .redis.mode "sentinel" }}
            - name: REDIS_MASTER_NAME
              value: {{ .redis.master.name }}
            - name: REDIS_SENTINEL_HOST
              value: {{ .redis.sentinel.host }}
            - name: REDIS_SENTINEL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: {{ .redis.secret.key }}
            {{- else if eq .redis.mode "cluster" }}
            - name: REDIS_CLUSTER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.cluster.secret.name }}
                  key: {{ .redis.cluster.secret.passwordKey }}
            - name: NODE_ADDRESSES
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.cluster.secret.name }}
                  key: {{ .redis.cluster.secret.endpointKey }}
            {{- else if eq .redis.mode "elasticache" }}
            - name: REDIS_STANDALONE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: REDIS_ENDPOINT
            - name: REDIS_STANDALONE_PORT
              value: "6379"
            - name: REDIS_STANDALONE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: {{ .redis.secret.key }}
            {{- else if eq .redis.mode "managed-standalone" }}
            - name: REDIS_STANDALONE_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_HOST
            - name: REDIS_STANDALONE_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PORT
            - name: REDIS_STANDALONE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: {{ .redis.secret.key }}
            - name: REDIS_USE_SSL
              value: {{ .redis.standalone.useSsl | default "false" | quote }}
            {{- else }}
            - name: REDIS_STANDALONE_HOST
              value: {{ .redis.standalone.host }}
            - name: REDIS_STANDALONE_PORT
              value: {{ .redis.standalone.port | quote }}
            - name: REDIS_STANDALONE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .redis.secret.name }}
                  key: {{ .redis.secret.key }}
            - name: REDIS_USE_SSL
              value: {{ .redis.standalone.useSsl | default "false" | quote }}
            {{- end }}
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .s3.secret.name }}
                  key: {{ .s3.secret.bucketNameKey }}
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .s3.secret.name }}
                  key: {{ .s3.secret.regionKey }}
            - name: S3_STORAGE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .s3.secret.name }}
                  key: {{ .s3.secret.endpointKey }}
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .s3.secret.name }}
                  key: {{ .s3.secret.accessKeyKey }}
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .s3.secret.name }}
                  key: {{ .s3.secret.secretKeyKey }}

          ports:
            - name: api
              containerPort: {{ .port }}
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 2
{{ end }}
{{ end }}
