{{ with .Values.explorerApi }}
{{ if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cf-explorer-api
spec:
  rules:
    - host: api.dev.preprod.metadata.cardanofoundation.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-api
                port:
                  number: {{ .port }}
{{ end }}
{{ end }}
