{{ with .Values.explorerApi }}
{{ if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cf-explorer-api
spec:
  rules:
    {{- if eq $.Values.network "mainnet" }}
    - host: "api.{{ $.Values.domain }}"
    {{- else }}
    - host: "api.{{ $.Values.network }}.{{ $.Values.domain }}"
    {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-api
                port:
                  number: {{ .port }}
  tls:
    - hosts:
        {{- if eq $.Values.network "mainnet" }}
        - "api.{{ $.Values.domain }}"
        {{- else }}
        - "api.{{ $.Values.network }}.{{ $.Values.domain }}"
        {{- end }}
{{ end }}
{{ end }}
