{{ with .Values.explorerFrontEnd }}
{{ if .enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cf-explorer-fe
spec:
  rules:
    - host: explorer.dev.preprod.metadata.cardanofoundation.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cf-explorer-fe
                port:
                  number: {{ .port }}
{{ end }}
{{ end }}
