{{ with .Values.kafka }}
{{ if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-explorer
  labels:
    app: kafka-explorer
spec:
  selector:
    app: kafka-explorer
  ports:
    - protocol: TCP
      name: api
      port: {{ .port }}
      targetPort: api
{{ end }}
{{ end }}
