{{ with .Values.keycloak }}
{{ if .enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8787"
      port: 8787
      targetPort: 8787
  selector:
    app: keycloak
{{ end }}
{{ end }}
