{{ with .Values.keycloak }}
{{ if .enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
  keycloak-setup.sh: |
    for envvar in WEB_ORIGIN REDIRECT_URI
    do
      sed -i "s|__${envvar}__|${!envvar}|" /opt/keycloak/data/import/realms.json.tpl
    done
    cp -a /opt/keycloak/data/import/realms.json.tpl /dest-imports/realms.json
{{ end }}
{{ end }}
