{{ with .Values.zookeeper }}
{{ if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-explorer
  labels:
    app: zookeeper-explorer
spec:
  selector:
    app: zookeeper-explorer
  ports:
    - protocol: TCP
      name: api
      port: {{ .port }}
      targetPort: api
{{ end }}
{{ end }}
