{{ with .Values.kafka }}
{{ if .enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-explorer
  template:
    metadata:
      labels:
        app: kafka-explorer
    spec:
      initContainers:
        - name: init
          command: [ "bash", "-x", "/configmap/init.sh" ]
          image: alpine
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-explorer
            - mountPath: /configmap
              name: kafka-init
      containers:
        - name: kafka-explorer
          image: "{{ .image.repository }}:{{ .image.tag }}"
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-explorer:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-explorer:9092,PLAINTEXT_HOST://localhost:29092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-explorer"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_BROKER_RACK
              value: "r1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_SCHEMA_REGISTRY_URL
              value: "schemaregistry:8085"
            - name: KAFKA_JMX_PORT
              value: "9991"
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "-1"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "-1"
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: "604800000"
          ports:
            - name: api
              containerPort: {{ .port }}
          livenessProbe:
            exec:
              command: [ '/bin/bash', '-c', 'nc -z localhost 9092' ]
            failureThreshold: 6
            periodSeconds: 10
          startupProbe:
            exec:
              command: [ '/bin/bash', '-c', 'nc -z localhost 9092' ]
            failureThreshold: 3
            periodSeconds: 10
            initialDelaySeconds: 30
      volumeMounts:
        - name: kafka-init
          configMap:
            name: kafka-init
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: "kafka-explorer"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .dbSize | default "8Gi" }}
  revisionHistoryLimit: 2
{{ end }}
{{ end }}
