{{ with .Values.postgresql }}
{{ if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.4.3
    chart: postgresql
    helm:
      values: |
        auth:
          username: cardano
          existingSecret: infra-secrets
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: postgres-user-password
            replicationPasswordKey: postgres-replication-password
          database: explorer_api
        primary:
          persistence:
            size: {{ .dbSize | default "8Gi" }}
          extendedConfiguration: |-
            wal_level=minimal
            archive_mode=off
            max_wal_senders=0
        shmVolume:
          enabled: true
          sizeLimit: "32Gi"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ $.Release.Namespace }}
    server: https://kubernetes.default.svc
{{ end }}
{{ end }}
