{{ if .Values.postgresql.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.4.3
    chart: postgresql
    helm:
      values: |
        auth:
          username: cardano-master
          password: CEGiDk52K4Awi2 # FIXME: this needs to disappear
          postgresPassword: CHANGEME # FIXME: this needs to disappear
          database: explorer_api
        shmVolume:
          enabled: true
          sizeLimit: "32Gi"
        extendedConf: |-
          max_locks_per_transaction=256
          shared_buffers=12GB
          effective_cache_size=31GB
          maintenance_work_mem=2GB
          checkpoint_completion_target=0.9
          checkpoint_timeout=1h
          synchronous_commit=off
          wal_buffers=16MB
          default_statistics_target=500
          random_page_cost=1.1
          effective_io_concurrency=500
          work_mem=1024GB
          min_wal_size=1GB
          max_wal_size=2GB
          max_parallel_workers_per_gather=4
          max_parallel_maintenance_workers=4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
{{ end }}
