{{ with .Values.postgresql }}
{{ if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.4.3
    chart: postgresql
    helm:
      values: |
        auth:
          username: cardano
          existingSecret: infra-secrets
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: postgres-user-password
            replicationPasswordKey: postgres-replication-password
          database: explorer_api
        primary:
          persistence:
            size: {{ .dbSize | default "8Gi" }}
          extendedConfiguration: |-
            effective_cache_size=12GB
            max_connections=250
            shared_buffers=4GB
            work_mem=2GB
            random_page_cost=1.1
            maintenance_work_mem=2GB
            shared_buffers=12GB
            checkpoint_completion_target=0.9
            synchronous_commit=off
            effective_io_concurrency=500
            wal_buffers=16MB
            min_wal_size=500MB
            max_wal_size=1GB
            max_parallel_workers_per_gather=4
            max_parallel_maintenance_workers=4
            track_counts=true
            autovacuum=on
            autovacuum_naptime=5min
            log_autovacuum_min_duration=0
        shmVolume:
          enabled: true
          sizeLimit: "32Gi"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ $.Release.Namespace }}
    server: https://kubernetes.default.svc
{{ end }}
{{ end }}
