{{ if index .Values "redis-cluster" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.6.1
    chart: redis-cluster
    helm:
      values: |
        auth:
          existingSecret: infra-other-secrets
          existingSecretPasswordKey: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
{{ end }}
