{{ with .Values.redis }}
{{ if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "redis-secret"
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  # generate 32 chars long random string, base64 encode it and then double-quote the result string.
  REDIS_MASTER_PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.10.3
    chart: redis
    helm:
      values: |
        auth:
          existingSecret: redis-secret
          existingSecretPasswordKey: REDIS_MASTER_PASSWORD
        replica:
          replicaCount: 0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: {{ $.Release.Namespace }}
    server: https://kubernetes.default.svc
{{ end }}
{{ end }}
