
# Source: cf-ledger-crawler/templates/zookeeper-statefulset.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-explorer
  template:
    metadata:
      labels:
        app: zookeeper-explorer
    spec:
      containers:
        - name: zookeeper-explorer
          image: "confluentinc/cp-zookeeper:5.1.2"
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper:22888:23888"
          ports:
            - name: api
              containerPort: 2181
          livenessProbe:
            httpGet:
              path: /
              port: api
          startupProbe:
            httpGet:
              path: /
              port: api
            failureThreshold: 30
            periodSeconds: 10
  revisionHistoryLimit: 2

