crawler:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-crawler"
    tag: "v0.2.4-25-g9282551"

  springProfiles: n2n,cluster

  port: 8080

  kafka:
    enabled: true
    bootstrapServer: kafka-explorer:9092

  redis:
    secretName: cf-explorer-redis-cluster
    cluster:
      hosts: cf-explorer-redis-cluster-headless:6379

    master:
      name: mymaster
    sentinel:
      host: cf-explorer-redis-headless

  crawler:
    name: dev-crawler
    blocks:
      topic: local.crawler.blocks
      rollbackTopic: local.crawler.rollback-blocks



  cardano:
    node:
      networkMagic: "764824073"
      address: relays-new.cardano-mainnet.iohk.io
      port: 3001

consumer:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-consumer"
    tag: "0.2.7"

  springProfiles: dev

  port: 8080

  postgres:
    host: cf-explorer-postgresql
    port: 5432
    user: cardano-master
    secretName: cf-explorer-postgresql
    dbName: explorer_api

  kafka:
    host: kafka-explorer
    port: 9092

  crawler:
    blocks:
      topic: local.crawler.blocks

  schema: mainnet
  maximumPoolSize: 64
  jdbcBatchSize: 500
  blocksBatchSize: 1000
  logLevel: debug

kafka:
  enabled: true
  image:
    repository: "confluentinc/cp-kafka"
    tag: "7.0.0"
  port: 9092
  service:
    type: ClusterIP
    nodePort: ""

zookeeper:
  enabled: true
  image:
    repository: "confluentinc/cp-zookeeper"
    tag: "5.1.2"
  port: 2181
  service:
    type: ClusterIP
    nodePort: ""

kafdrop:
  enabled: true
  replicas: 1
  image:
    repository: "obsidiandynamics/kafdrop"
    tag: "latest"
  port: 9000

redis-cluster:
  password: qfIIf4Tc8Z
#  cluster:
#    nodes: 6
#    replicas: 1

postgresql:
  auth:
    username: cardano-master
    postgresPassword: CHANGEME
    database: explorer_api
  shmVolume:
    enabled: true
    sizeLimit: "32Gi"
  extendedConf: |-
    max_locks_per_transaction=256
    shared_buffers=12GB
    effective_cache_size=31GB
    maintenance_work_mem=2GB
    checkpoint_completion_target=0.9
    checkpoint_timeout=1h
    synchronous_commit=off
    wal_buffers=16MB
    default_statistics_target=500
    random_page_cost=1.1
    effective_io_concurrency=500
    work_mem=1024GB
    min_wal_size=1GB
    max_wal_size=2GB
    max_parallel_workers_per_gather=4
    max_parallel_maintenance_workers=4
