explorerApi:
  enabled: true
  epochDays: 1
  postgres:
    schema: preview
  monitoringEnabled: true
  network: preview

  byronGenesisFile: /app/genesis/preview/byron-genesis.json
  shelleyGenesisFile: /app/genesis/preview/shelley-genesis.json

explorerRewardsApi:
  enabled: true
  postgres:
    schema: preview
  monitoringEnabled: true
  network: preview
  koios:
    baseUrl: "https://koios-api.pro.dandelion-preview.eu-west-1.metadata.dev.cf-deployments.org/rpc/"

explorerAuthentication:
  enabled: true
  postgres:
    schema: preview-auth
  monitoringEnabled: true

explorerFrontEnd:
  enabled: true

consumerSchedules:
  enabled: true
  postgres:
    schema: preview
  monitoringEnabled: true
  network: preview

  drepInfoJobEnabled: true
  governanceInfoJobEnabled: true
  governanceActionMetadataJobEnabled: true

  tokenMetadataUrl: "https://github.com/input-output-hk/metadata-registry-testnet.git"
  tokenMetadataFolder: "/registry"
