crawler:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-crawler"
    tag: "v0.2.4-25-g9282551"

  springProfiles: n2n,cluster

  port: 8080

  kafka:
    enabled: true
    bootstrapServer: kafka-explorer:9092

  redis:
    secretName: cf-explorer-redis-cluster
    cluster:
      hosts: cf-explorer-redis-cluster-headless:6379

    master:
      name: mymaster
    sentinel:
      host: cf-explorer-redis-headless

  crawler:
    name: dev-crawler
    blocks:
      topic: local.crawler.blocks
      rollbackTopic: local.crawler.rollback-blocks

  networkMagic: 764824073

  node:
    address: relays-new.cardano-mainnet.iohk.io
    port: 3001

kafka:
  enabled: true
  image:
    repository: "confluentinc/cp-kafka"
    tag: "7.0.0"
  port: 9092
  service:
    type: ClusterIP
    nodePort: ""

zookeeper:
  enabled: true
  image:
    repository: "confluentinc/cp-zookeeper"
    tag: "5.1.2"
  port: 2181
  service:
    type: ClusterIP
    nodePort: ""

kafdrop:
  enabled: true
  replicas: 1
  image:
    repository: "obsidiandynamics/kafdrop"
    tag: "latest"
  port: 9000

#redis-cluster:
#  cluster:
#    nodes: 6
#    replicas: 1
