crawler:

  springProfiles: n2n,cluster,kafka

  monitoringEnabled: true

  crawler:
    name: preprod-crawler

  cardano:
    node:
      networkMagic: "1"
      address: preprod-node.world.dev.cardano.org
      port: 30000

  redis:
    ## Redis Standalone Values Example
    mode: cluster
    cluster:
      secret:
        name: infra-secrets
        passwordKey: REDIS_MASTER_PASSWORD
        endpointKey: REDIS_ENDPOINT

consumer:

  springProfiles: dev

  monitoringEnabled: true
  
  network: preprod

  postgres:
    schema: preprod

  networkMagic: "1"

explorerApi:
  enabled: true
  springProfiles: dev,cluster
  postgres:
    schema: preprod
  redis:
    mode: cluster
    cluster:
      secret:
        name: infra-secrets
        passwordKey: REDIS_MASTER_PASSWORD
        endpointKey: REDIS_ENDPOINT
  monitoringEnabled: true

explorerRewardsApi:
  enabled: true
  postgres:
    schema: preprod
  monitoringEnabled: true

explorerAuthentication:
  enabled: true
  springProfiles: dev,cluster
  postgres:
    schema: preprod-auth
  redis:
    ## Redis Standalone Values Example
    mode: cluster
    cluster:
      secret:
        name: infra-secrets
        passwordKey: REDIS_MASTER_PASSWORD
        endpointKey: REDIS_ENDPOINT
  monitoringEnabled: true

explorerFrontEnd:
  enabled: true

consumerSchedules:
  enabled: true
  postgres:
    schema: preprod
  monitoringEnabled: true
  network: preprod
