crawler:

  monitoringEnabled: true

  crawler:
    name: preprod-crawler

  cardano:
    node:
      networkMagic: "1"
      address: preprod-node.world.dev.cardano.org
      port: 30000

consumer:

  springProfiles: local

  monitoringEnabled: true
  
  network: preprod

  postgres:
    schema: preprod

  networkMagic: "1"

explorerApi:
  enabled: true
  postgres:
    schema: preprod
  monitoringEnabled: true

explorerAuthentication:
  enabled: true
  postgres:
    schema: preprod
  monitoringEnabled: true

explorerFrontEnd:
  enabled: true
