crawler:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-crawler"
    tag: "0.2.6"

  springProfiles: n2n,standalone,kafka

  port: 8080

  monitoringEnabled: false

  kafka:
    useSsl: "false"
    bootstrapServersSecret:
      name: kafka-secrets
      key: KAFKA_BOOTSTRAP_SERVERS_TLS

  redis:
    ## Redis Standalone Values Example
    mode: standalone
    secret:
      name: redis-secrets
      key: REDIS_MASTER_PASSWORD
    standalone:
      host: redis-headless
      port: 6379

    ## Redis Cluster Values Example
    # mode: cluster
    # secretName: cf-explorer-infra-redis-cluster
    # cluster:
    #   hosts: cf-explorer-infra-redis-cluster-headless:6379

    master:
      name: mymaster
    sentinel:
      host: cf-explorer-redis-headless

  crawler:
    name: dev-crawler
    blocks:
      topic: local.crawler.blocks
      rollbackTopic: local.crawler.rollback-blocks



  cardano:
    node:
      networkMagic: "764824073"
      address: relays-new.cardano-mainnet.iohk.io
      port: 3001

consumer:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-consumer"
    tag: "0.2.13"

  springProfiles: aws, redis-standalone, caching

  port: 8080

  monitoringEnabled: false

  redis:
    ## Redis Standalone Values Example
    mode: standalone
    secret:
      name: redis-secrets
      key: REDIS_MASTER_PASSWORD
    standalone:
      host: redis-headless
      port: 6379

  postgres:
    schema: mainnet
    secret:
      name: postgres-secrets
      userKey: POSTGRES_USER
      hostKey: POSTGRES_HOST
      portKey: POSTGRES_PORT
      dbKey: POSTGRES_DB
      passwordKey: POSTGRES_PASSWORD

  jpa:
    showSql: false

  kafka:
    useSsl: "false"
    bootstrapServersSecret:
      name: kafka-secrets
      key: KAFKA_BOOTSTRAP_SERVERS_TLS

  crawler:
    blocks:
      topic: local.crawler.blocks

  maximumPoolSize: 64
  jdbcBatchSize: 500
  blocksBatchSize: 1000
  logLevel: debug
  network: mainnet
  networkMagic: "764824073"

explorerApi:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-explorer-api"
    tag: "0.3.9"

  springProfiles: dev,standalone,koios,s3

  port: 8080

  monitoringEnabled: false

  service:
    type: ClusterIP
  #    nodePort: "30092"

  redis:
    ## Redis Standalone Values Example
    mode: standalone
    secret:
      name: redis-secrets
      key: REDIS_MASTER_PASSWORD
    standalone:
      host: redis-headless
      port: 6379

  kafka:
    useSsl: "false"
    bootstrapServersSecret:
      name: kafka-secrets
      key: KAFKA_BOOTSTRAP_SERVERS_TLS
    reportsTopic: dev.explorer.api.reports

    ## Redis Cluster Values Example
    # mode: cluster
    # secretName: cf-explorer-infra-redis-cluster
    # cluster:
    #   hosts: cf-explorer-infra-redis-cluster-headless:6379

  explorerRewardsUrl: http://cf-explorer-rewards-api

  postgres:
    schema: mainnet
    secret:
      name: postgres-secrets
      userKey: POSTGRES_USER
      hostKey: POSTGRES_HOST
      portKey: POSTGRES_PORT
      dbKey: POSTGRES_DB
      passwordKey: POSTGRES_PASSWORD

  s3:
    secret:
      name: infra-secrets
      accessKeyKey: REPORT_S3_ACCESS_KEY
      secretKeyKey: REPORT_S3_SECRET_KEY
      bucketNameKey: REPORT_S3_BUCKET_NAME
      regionKey: REPORT_S3_REGION
      endpointKey: REPORT_S3_STORAGE_ENDPOINT

  tokenLogoEndpoint: https://dev-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/

explorerRewardsApi:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-explorer-rewards"
    tag: "0.1.1-SNAPSHOT"

  springProfiles: dev,koios

  port: 8080

  monitoringEnabled: false

  service:
    type: ClusterIP
  #    nodePort: "30092"

  postgres:
    schema: mainnet
    secret:
      name: postgres-secrets
      userKey: POSTGRES_USER
      hostKey: POSTGRES_HOST
      portKey: POSTGRES_PORT
      dbKey: POSTGRES_DB
      passwordKey: POSTGRES_PASSWORD

  network: mainnet

  koios:
    baseUrlEnabled: false
    baseUrl: ""

explorerAuthentication:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-explorer-authentication"
    tag: "v0.1.1-7-g2e0c779"

  springProfiles: dev, standalone, ses

  port: 8080

  monitoringEnabled: false

  service:
    type: ClusterIP
  #    nodePort: "30092"

  redis:
    ## Redis Standalone Values Example
    mode: standalone
    secret:
      name: redis-secrets
      key: REDIS_MASTER_PASSWORD
    standalone:
      host: redis-headless
      port: 6379

  postgres:
    schema: mainnet-auth
    secret:
      name: postgres-secrets
      userKey: POSTGRES_USER
      hostKey: POSTGRES_HOST
      portKey: POSTGRES_PORT
      dbKey: POSTGRES_DB
      passwordKey: POSTGRES_PASSWORD

  region:
    secret:
      name: infra-secrets
      key: AWS_REGION

  flywayEnabled: true
  swaggerClientUrl: https://{{ .Values.domain }}/en
  swaggerServerUrl: http://localhost:8021
  emailFrom: admin@metadata.dev.cf-deployments.org
  emailFromName: Cardano Foundation

explorerFrontEnd:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-explorer-frontend"
    tag: "0.3.2"

  reactAppApiUrl: "https://api.{{ .Values.domain }}/api/v1"
  reactAppPreProdAppUrl: "https://{{ .Values.network }}.{{ .Values.domain }}"
  reactAppPreviewAppUrl: "https://{{ .Values.network }}.{{ .Values.domain }}"
  reactAppMainnetAppUrl: "https://{{ .Values.domain }}"
  reactAppAuthUrl: "https://auth-api.{{ .Values.domain }}/api/v1"
  reactAppNetwork: "{{ .Values.network }}"
  reactAppCardanoNewsUrl: "https://cardanofoundation.org/en/news/"

  port: 80

  service:
    type: ClusterIP
  #    nodePort: "30092"

  jira:
    widget:
      secretName: infra-secrets
      secretKey: REACT_APP_JSD_WIDGET_KEY

consumerSchedules:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-consumer-schedules"
    tag: "0.2.2"

  springProfiles: dev,standalone,koios,s3

  port: 8080

  monitoringEnabled: false

  postgres:
    schema: mainnet
    secret:
      name: postgres-secrets
      userKey: POSTGRES_USER
      hostKey: POSTGRES_HOST
      portKey: POSTGRES_PORT
      dbKey: POSTGRES_DB
      passwordKey: POSTGRES_PASSWORD

  kafka:
    useSsl: "false"
    bootstrapServersSecret:
      name: kafka-secrets
      key: KAFKA_BOOTSTRAP_SERVERS_TLS
    reportsTopic: dev.explorer.api.reports

  redis:
    ## Redis Standalone Values Example
    mode: standalone
    secret:
      name: redis-secrets
      key: REDIS_MASTER_PASSWORD
    standalone:
      host: redis-headless
      port: 6379

  s3:
    secret:
      name: infra-secrets
      report:
        accessKeyKey: REPORT_S3_ACCESS_KEY
        secretKeyKey: REPORT_S3_SECRET_KEY
        bucketNameKey: REPORT_S3_BUCKET_NAME
        regionKey: REPORT_S3_REGION
        endpointKey: REPORT_S3_STORAGE_ENDPOINT
      tokenLogo:
        accessKeyKey: TOKEN_LOGO_S3_ACCESS_KEY
        secretKeyKey: TOKEN_LOGO_S3_SECRET_KEY
        bucketNameKey: TOKEN_LOGO_S3_BUCKET_NAME
        regionKey: TOKEN_LOGO_S3_REGION
        endpointKey: TOKEN_LOGO_S3_STORAGE_ENDPOINT

  checkRewardUrl: http://cf-explorer-rewards-api/api/v1/rewards/fetch
  checkPoolHistoryUrl: http://cf-explorer-rewards-api/api/v1/pool-history/fetch

  network: mainnet

  tokenLogoEndpoint: https://dev-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/

cardanoNewsApi:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cardano-news-api"
    tag: "0.2.1"

  port: 8080

keycloak:
  enabled: true
  image:
    repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/keycloak-spi
    tag: 1.0.0-PR91
  setupImage:
    repository: pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/keycloak-spi
    tag: 0.1.15-SNAPSHOT-PR110
  adminUser: null
  hostname: null
  adminSecretKey: null
  adminSecretName: null
  frontendDomainPublicUrl: null
  postgresDbSecretKey: null
  postgresHostSecretKey: null
  postgresPassSecretKey: null
  postgresSecretName: null
  postgresUserSecretKey: null
  redirectUri: null
  port: 8080
