crawler:

  monitoringEnabled: true

  crawler:
    name: preprod-crawler

  cardano:
    node:
      networkMagic: "1"
      address: preprod-node.world.dev.cardano.org
      port: 30000

consumer:

  monitoringEnabled: true
  
  network: preprod

  postgres:
    schema: preprod

  networkMagic: "1"

explorerApi:
  enabled: true
  postgres:
    schema: preprod
  monitoringEnabled: true
  network: preprod

  byronGenesisFile: /app/genesis/preprod/byron-genesis.json
  shelleyGenesisFile: /app/genesis/preprod/shelley-genesis.json

  apiBolnisiOffchainUrl: "https://offchain.stg.cf-bolnisi-preprod.eu-west-1.metadata.dev.cf-deployments.org/api/v1/storage/objectUrl/georgian-wine/{cid}"
  apiBolnisiPublicKeyUrl: "https://api.stg.cf-bolnisi-preprod.eu-west-1.metadata.dev.cf-deployments.org/api/v1/pubkeys/{wineryId}/v/0"

explorerRewardsApi:
  enabled: true
  postgres:
    schema: preprod
  monitoringEnabled: true
  network: preprod
  koios:
    baseUrl: "https://koios-api.pro.dandelion-preprod.eu-west-1.metadata.dev.cf-deployments.org/rpc/"

explorerAuthentication:
  enabled: true
  postgres:
    schema: preprod-auth
  monitoringEnabled: true

explorerFrontEnd:
  enabled: true
  reactAppBolnisiName: "https://minio.stg.cf-bolnisi-preprod.eu-west-1.metadata.dev.cf-deployments.org/georgian-wine/public/winerymapping.json"

consumerSchedules:
  enabled: true
  postgres:
    schema: preprod
  monitoringEnabled: true
  network: preprod
