crawler:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-crawler"
    tag: "v0.2.4-25-g9282551"

  springProfiles: n2n,cluster

  port: 8080

  kafka:
    enabled: true
    bootstrapServer: kafka-explorer:9092

  redis:
    secretName: cf-explorer-infra-redis-cluster
    cluster:
      hosts: cf-explorer-infra-redis-cluster-headless:6379

    master:
      name: mymaster
    sentinel:
      host: cf-explorer-redis-headless

  crawler:
    name: dev-crawler
    blocks:
      topic: local.crawler.blocks
      rollbackTopic: local.crawler.rollback-blocks



  cardano:
    node:
      networkMagic: "764824073"
      address: relays-new.cardano-mainnet.iohk.io
      port: 3001

consumer:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-consumer"
    tag: "0.2.8"

  springProfiles: dev

  port: 8080

  postgres:
    host: cf-explorer-infra-postgresql
    port: 5432
    user: cardano-master
    secretName: cf-explorer-infra-postgresql
    dbName: explorer_api

  kafka:
    host: kafka-explorer
    port: 9092

  crawler:
    blocks:
      topic: local.crawler.blocks

  schema: mainnet
  maximumPoolSize: 64
  jdbcBatchSize: 500
  blocksBatchSize: 1000
  logLevel: debug

explorerApi:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-explorer-api"
    tag: "v0.3.7-SNAPSHOT-2-ga2f4854"

  springProfiles: dev, cluster

  port: 8080

  service:
    type: ClusterIP
  #    nodePort: "30092"

  redis:
    secretName: cf-explorer-infra-redis-cluster
    cluster:
      hosts: cf-explorer-infra-redis-cluster-headless:6379

  postgres:
    host: cf-explorer-infra-postgresql
    port: 5432
    user: cardano-master
    secretName: cf-explorer-infra-postgresql
    dbName: explorer_api

explorerFrontEnd:
  enabled: true
  replicas: 1

  image:
    repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-explorer-frontend"
    tag: "0.3.2"

    reactAppApiUrl: http://cf-explorer-api:8080/api/v1
#    reactAppApiUrl: https://dev.cf-explorer-monolith-mainnet.metadata.dev.cf-deployments.org:8080/api/v1
    reactAppPreProdApiUrl: https://dev.cf-explorer-monolith-testnets.metadata.dev.cf-deployments.org:18000/api/v1
    reactAppPreviewUrl: https://dev.cf-explorer-monolith-testnets.metadata.dev.cf-deployments.org:18100/api/v1
    reactAppTestnetApiUrl: https://dev.cf-explorer-monolith-testnets.metadata.dev.cf-deployments.org:18200/api/v1
    reactAppMainnetApiUrl: https://dev.cf-explorer-monolith-mainnet.metadata.dev.cf-deployments.org:8080/api/v1
    reactAppAuthUrl: https://dev.cf-explorer-monolith-mainnet.metadata.dev.cf-deployments.org:8080/api/v1

  port: 1102

  service:
    type: ClusterIP
  #    nodePort: "30092"