apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.28.1
    chart: kube-prometheus-stack
    helm:
      parameters:
        - name: "grafana.ingress.enabled"
          value: "true"
        - name: "grafana.ingress.hosts[0]"
          value: grafana.{{ .Values.stage }}.{{ .Values.network }}.online

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  destination:
    namespace: observe
    server: {{ .Values.spec.destination.server }}
