apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 0.4.0
    chart: eck-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
#      - ServerSideApply=true

  destination:
    namespace: elastic
    server: {{ .Values.spec.destination.server }}
