{{ if index .Values "kube-prometheus-stack" "enabled" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    {{- with index .Values "kube-prometheus-stack" }}
    targetRevision: {{ .version }}
    {{- end }}
    chart: kube-prometheus-stack
    helm:
      parameters:
        - name: "grafana.ingress.enabled"
          value: "true"
        - name: "grafana.ingress.hosts[0]"
          value: grafana.{{ $.Values.domain }}
      values: |
        grafana:
          plugins:
            - grafana-singlestat-panel
          alerting:
            rules.yaml:
{{ (.Files.Glob "grafana-provisioning/alerting/rules.yaml").AsConfig | indent 14 }}
            contactpoints.yaml:
{{ (.Files.Glob "grafana-provisioning/alerting/contactpoints.yaml").AsConfig | indent 14 }}
            policies.yaml:
{{ (.Files.Glob "grafana-provisioning/alerting/policies.yaml").AsConfig | indent 14 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  destination:
    namespace: observe
    server: {{ .Values.spec.destination.server }}
{{ end }}
