{{ if index .Values "elastic-stack" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-eck-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repoURL | default "https://github.com/cardano-foundation/cf-explorer.git" }}
    targetRevision: {{ .Values.git.targetRevision | default "HEAD" }}
    path: charts/elastic-eck-stack
    helm:
      parameters:
        - name: "domain"
          value: {{ .Values.domain }}

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  destination:
    namespace: elastic-stack
    server: {{ .Values.spec.destination.server }}
  {{ end }}
