{{ if index .Values "grafana-customizations" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-customizations
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repoURL | default "https://github.com/cardano-foundation/cf-explorer.git" }}
    targetRevision: {{ .Values.git.targetRevision | default "HEAD" }}
    path: charts/grafana-customizations

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: "*"
      kind: "ConfigMap"
      jqPathExpressions:
        - '.data.contactpoints.yaml'

  destination:
    namespace: observe
    server: {{ .Values.spec.destination.server }}
{{ end }}
