{{ if .Values.postgres.operator.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
    targetRevision: 1.11.0
    chart: postgres-operator
    helm:
      values: |
        configKubernetes:
          enable_pod_antiaffinity: true
        configAwsOrGcp:
          aws_region: eu-west-1
          wal_s3_bucket: uat-cf-explorer-preview-pg-backups
        configLogicalBackup:
          logical_backup_cronjob_environment_secret: logical-backup-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
{{ end }}