{{ if index .Values "cf-network-monitoring-aggregator" "enabled" }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-network-monitoring-aggregator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.git.repoURL | default "https://github.com/cardano-foundation/cf-explorer.git" }}
    targetRevision: {{ .Values.git.targetRevision | default "HEAD" }}
    path: charts/cf-network-monitoring-aggregator
    helm:
      parameters:
        - name: "network"
          value: {{ .Values.network }}
      {{- with index .Values "cf-network-monitoring-aggregator" "values" }}
      values: |
{{ toYaml . | indent 8 }}
      {{- end }}

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

  destination:
    namespace: cf-explorer
    server: {{ .Values.spec.destination.server }}
{{ end }}
