stage: dev

network: preprod

domain: dev.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    dbSize: 150Gi
  kafka:
    dbSize: 20Gi

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: dev.cf-explorer-preprod.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: dev.cf-explorer-preprod.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: dev.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org
    crawler:
      enabled: true
      image:
        tag: "0.2.12"
      kafka:
        bootstrapServerSecret:
          name: kafka-secrets
    consumer:
      enabled: true
      image:
        tag: "0.3.14"
    explorerApi:
      enabled: true
      image:
        tag: "0.3.30"
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.7-SNAPSHOT"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.1.13"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.4.20"
      reactAppPreProdAppUrl: "https://dev.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://dev.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://dev.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.dev.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.2.12"

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.dev.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org 
