git:
  targetRevision: main

stage: pro

network: preview

domain: preview.beta.explorer.cardano.org

cf-explorer-infra:
  enabled: true
  postgresql:
    dbSize: 450Gi
    nodeSelector:
      node.kubernetes.io/role: postgres
    tolerations:
      - key: role
        value: postgres
        operator: Equal
        effect: PreferNoSchedule

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop-1_7_0"
    localCardanoNode:
      enabled: true
      volumeSize: 20Gi
      network: "preview"
      sleep: true
    indexer:
      enabled: true
      replicaCount: 0
      image:
        tag: "0.1.0"
      postgres:
        secretName: postgres-secrets-local
    aggregation:
      enabled: true
      replicaCount: 0
      image:
        tag: "0.1.0"
      db:
        maximum_pool_size: 60
      postgres:
        secretName: postgres-secrets-local
        dbSchema: preview
      store:
        account:
          history_cleanup_enabled: "false"

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: preview.beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-preview.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-preview.us-east-1.beta.explorer.cardano.org
    explorerApi:
      enabled: true
      replicas: 1
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
      image:
        tag: "1.3.0-PR1310-de128b6-10295491786"
      swagger:
        enabled: false
    explorerRewardsApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.3.0-PR103-0cd6aab-9754219477"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.9.0-PR132-394f1ba-9743398271"
      emailFrom: "admin@beta.explorer.cardano.org"
      keycloakServerUrl: "https://keycloak.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.6.0-PR-f71b692-10285504534"
      reactAppFfGlobalIsConwayEra: "true"
      reactAppFfGlobalIsConwayBootstrapDataAvailable: "true"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/api/v1"
      # temporary
      #reactAppAdaHandleApi: "https://adahandle-resolver.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/api/v1"
      #reactAppApiUrl: "https://api.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/api/v1"
      #reactAppWsUrl: "wss://api.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/ws"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: true
      replicas: 0
      image:
        tag: "1.3.0-PR517-8d4bff0-10264448294"
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://preview.beta.explorer.cardano.org
      webOrigin: https://preview.beta.explorer.cardano.org
      redirectUri: https://preview.beta.explorer.cardano.org/*
      forwardEventUrl: https://preview.beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    ingress:
      enabled: true
      additionalDomains:
        - adahandle-resolver.pro.cf-explorer-preview.us-east-1.beta.explorer.cardano.org
        - adahandle-resolver.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org
        - adahandle-resolver.preview.global.beta.explorer.cardano.org
    springProfiles: preview,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org
