stage: pro

network: mainnet

domain: beta.explorer.cardano.org

cf-explorer-infra:
  enabled: true
  redis:
    enabled: false
  postgresql:
    enabled: true
    dbSize: 4500Gi
    nodeSelector:
      node.kubernetes.io/role: postgres
    tolerations:
      - key: role
        value: postgres
        operator: Equal
        effect: PreferNoSchedule

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop-1_7_0"
    localCardanoNode:
      enabled: true
      volumeSize: 200Gi
      network: "mainnet"
    indexer:
      enabled: true
      replicaCount: 1
      image:
        tag: "0.1.0"
      postgres:
        secretName: postgres-secrets-local
    aggregation:
      enabled: true
      replicaCount: 1
      image:
        tag: "0.1.0"
#      db:
#        maximum_pool_size: 60
      postgres:
        secretName: postgres-secrets-local
        dbSchema: mainnet
      store:
        account:
          history_cleanup_enabled: "false"

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-mainnet.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org
    explorerApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.7.0-PR1349-6a9dcdb-10594521919"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
      swagger:
        enabled: false
    explorerRewardsApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.5.0-593f9b1-10371126638"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "1.4.0-1e3e78d-10371096098"
      emailFrom: "admin@beta.explorer.cardano.org"
      keycloakServerUrl: "https://keycloak.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.7.0-main-7a4d7e5-10371257901"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/api/v1"
      # temporary
      reactAppApiUrl: "https://api.pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org/api/v1"
      reactAppWsUrl: "wss://api.pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org/ws"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: true
      replicas: 1
      image:
        tag: "1.7.0-PR536-7f029a9-10645800258"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/

      # switch off
      tokenTxCountJobEnabled: true
      tokenInfoJobEnabled: true
      aggAnalyticJobEnabled: true
      latestTokenBalanceJobEnabled: true
      nativeScriptInfoJobEnabled: true
      smartContractInfoJobEnabled: true
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://beta.explorer.cardano.org
      webOrigin: https://beta.explorer.cardano.org
      redirectUri: https://beta.explorer.cardano.org/*
      forwardEventUrl: https://beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    ingress:
      enabled: true
      additionalDomains:
        - adahandle-resolver.pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org
        - adahandle-resolver.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
        - adahandle-resolver.mainnet.global.beta.explorer.cardano.org
    springProfiles: mainnet,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
