stage: pro

network: sanchonet

domain: sanchonet.beta.explorer.cardano.org

cf-explorer-infra:
  enabled: true
  postgresql:
    dbSize: 100Gi
  kafka:
    enabled: true

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "chore/add-cardano-node-to-helm-chart"
    image:
      repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
      tag: "0d6d20f-8246831004"
    ingress:
     enabled: false
    useLocalCardanoNode: false
    localCardanoNode:
      image:
        repository: ghcr.io/intersectmbo/cardano-node
        tag: 8.8.0-pre
      enabled: true
      network: "sanchonet"

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: sanchonet.beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-sanchonet.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-sanchonet.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-sanchonet.us-east-1.beta.explorer.cardano.org
    explorerApi:
      enabled: true
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      image:
        tag: "0.5.0-sanchonet-PR919"
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.7"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.5.0-SNAPSHOT-sanchonet-PR118"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.5.3-PR2693"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/api/v1"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.5.0-sanchonet-PR278"
      tokenLogoEndpoint: https://stg-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-sanchonet.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://sanchonet.beta.explorer.cardano.org
      webOrigin: https://sanchonet.beta.explorer.cardano.org
      redirectUri: https://sanchonet.beta.explorer.cardano.org/*
      forwardEventUrl: https://sanchonet.beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    springProfiles: sanchonet,postgres
    image:
      tag: "0.1.2"

kube-prometheus-stack:
  enabled: true
  version: 55.4.0

argo-cd:
  crds:
    install: false
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-sanchonet.eu-west-1.beta.explorer.cardano.org
