stage: dev

network: mainnet

domain: dev.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    dbSize: 750Gi
  kafka:
    dbSize: 750Gi

cf-explorer:
  enabled: true
  values:
    crawler:
      enabled: true
      image:
        tag: "0.2.7"
    consumer:
      enabled: true
      image:
        tag: "v0.3.0-3-gc69bb0c"
    explorerApi:
      image:
        tag: "0.3.11"
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.1"
    explorerAuthentication:
      replicas: 1
      image:
        tag: "0.1.3"
    explorerFrontEnd:
      image:
        tag: "0.3.5"
    consumerSchedules:
      enabled: false
      image:
        tag: "0.2.2"

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.dev.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
