stage: stg

network: preprod

domain: stg.cf-explorer-preprod.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: false

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: stg.cf-explorer-preprod.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: stg.cf-explorer-preprod.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: stg.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org
    crawler:
      enabled: true
      image:
        tag: "0.2.11"
      springProfiles: n2n,cluster,kafka
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      redis:
        mode: cluster
        cluster:
          secret:
            name: redis-secrets
            passwordKey: REDIS_MASTER_PASSWORD
            endpointKey: REDIS_ENDPOINT
    consumer:
      enabled: true
      image:
        tag: "0.3.8"
      springProfiles: aws
      redis:
        mode: cluster
        cluster:
          secret:
            name: redis-secret
            passwordKey: REDIS_MASTER_PASSWORD
            endpointKey: REDIS_ENDPOINT
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
    explorerApi:
      enabled: true
      s3:
        bucketName: stg-cf-explorer-preprod-reports
        region: eu-west-1
        endpoint: https://s3-eu-west-1.amazonaws.com
        secret:
          name: infra-secrets
          accessKeyKey: S3_ACCESS_KEY
          secretKeyKey: S3_SECRET_KEY
      image:
        tag: "0.3.21"
      springProfiles: dev,cluster,koios,s3
      redis:
        mode: cluster
        cluster:
          secret:
            name: redis-secrets
            passwordKey: REDIS_MASTER_PASSWORD
            endpointKey: REDIS_ENDPOINT
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.6"
    explorerAuthentication:
      enabled: false
      replicas: 1
      image:
        tag: "0.1.7"
      redis:
        mode: cluster
        cluster:
          secret:
            name: redis-secret
            passwordKey: REDIS_MASTER_PASSWORD
            endpointKey: REDIS_ENDPOINT
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.4.8"
      reactAppPreProdAppUrl: "https://stg.cf-explorer-preprod.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.stg.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    consumerSchedules:
      enabled: true
      s3:
        bucketName: stg-cf-explorer-preprod-reports
        region: eu-west-1
        endpoint: https://s3-eu-west-1.amazonaws.com
        secret:
          name: infra-secrets
          accessKeyKey: S3_ACCESS_KEY
          secretKeyKey: S3_SECRET_KEY
      image:
        tag: "0.2.8"
      springProfiles: dev,cluster,koios,s3
      redis:
        mode: cluster
        cluster:
          secret:
            name: redis-secrets
            passwordKey: REDIS_MASTER_PASSWORD
            endpointKey: REDIS_ENDPOINT
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.stg.cf-explorer-preprod.metadata.dev.cf-deployments.org
