stage: stg

network: preview

domain: stg.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    enabled: false
  kafka:
    dbSize: 150Gi

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: stg.cf-explorer-preview.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: stg.cf-explorer-preview.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: stg.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org
    crawler:
      enabled: true
      image:
        tag: "0.2.12"
    consumer:
      enabled: true
      image:
        tag: "0.3.14"
    explorerApi:
      enabled: true
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      image:
        tag: "0.3.31"
      tokenLogoEndpoint: https://stg-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.7-SNAPSHOT"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.1.13"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.4.24"
      reactAppPreProdAppUrl: "https://stg.cf-explorer-preprod.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.stg.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.2.12"
      tokenLogoEndpoint: https://stg-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.stg.cf-explorer-preview.metadata.dev.cf-deployments.org
