stage: stg

network: mainnet

domain: stg.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: false

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: stg.cf-explorer-mainnet.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: stg.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
    crawler:
      enabled: true
      image:
        tag: "0.2.12"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
    consumer:
      enabled: true
      image:
        tag: "0.3.14"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
    explorerApi:
      enabled: true
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      image:
        tag: "0.3.31"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://stg-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.7-SNAPSHOT"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.1.13"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.4.22"
      reactAppPreProdAppUrl: "https://stg.cf-explorer-preprod.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.stg.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.2.12"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://stg-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org
