stage: stg

network: mainnet

domain: pro.cf-explorer-mainnet.iris.cardano.org

cf-explorer-infra:
  enabled: true
  postgresql:
    enabled: false
  redis:
    enabled: false
  kafka:
    enabled: false

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: iris.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-mainnet.global.iris.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-mainnet.eu-west-1.iris.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-mainnet.us-east-1.iris.cardano.org
    crawler:
      enabled: true
      image:
        tag: "0.2.7"
      redis:
        mode: standalone
    consumer:
      enabled: true
      #springProfiles: aws,redis-standalone
      image:
        tag: "0.3.4"
      redis:
        mode: standalone
    explorerApi:
      s3:
        bucketName: pro-cf-explorer-mainnet-reports
        region: eu-west-1
        endpoint: https://s3-eu-west-1.amazonaws.com
        secret:
          name: infra-secrets
          accessKeyKey: S3_ACCESS_KEY
          secretKeyKey: S3_SECRET_KEY
      image:
        tag: "0.3.14"
      redis:
        mode: standalone
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.2"
    explorerAuthentication:
      replicas: 1
      image:
        tag: "0.1.6"
      redis:
        mode: standalone
    explorerFrontEnd:
      image:
        tag: "0.4.4"
      reactAppPreProdAppUrl: "https://preprod.iris.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.iris.cardano.org"
      reactAppMainnetAppUrl: "https://iris.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-mainnet.eu-west-1.iris.cardano.org/api/v1"
    consumerSchedules:
      enabled: true
      s3:
        bucketName: pro-cf-explorer-mainnet-reports
        region: eu-west-1
        endpoint: https://s3-eu-west-1.amazonaws.com
        secret:
          name: infra-secrets
          accessKeyKey: S3_ACCESS_KEY
          secretKeyKey: S3_SECRET_KEY
      image:
        tag: "0.2.7"
      redis:
        mode: standalone

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-mainnet.eu-west-1.iris.cardano.org
