stage: pro

network: mainnet

domain: beta.explorer.cardano.org

cf-explorer-infra:
  enabled: false

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop"
    useLocalCardanoNode: true
    localCardanoNode:
      enabled: true
      volumeSize: 200Gi
      network: "mainnet"
      image:
        repository: ghcr.io/intersectmbo/cardano-node
        tag: 8.9.2
    indexer:
      enabled: true
      replicaCount: 1
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
        tag: "79c7166-9483361920"
      hikari:
        maxLifetime: 10000
    blocks:
      batchSize: "10"
    aggregation:
      enabled: true
      replicaCount: 1
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync-aggregation"
        tag: "79c7166-9483361920"
      hikari:
        maxLifetime: 1000
      db:
        maximum_pool_size: 60
      postgres:
        dbSchema: mainnet
      store:
        account:
          history_cleanup_enabled: "false"
        executor:
          enable_parallel_processing: "true"
          use_virtual_thread_for_batch_processing: "true"
          use_virtual_thread_for_event_processing: "true"

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-mainnet.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org
    explorerApi:
      enabled: true
      replicas: 1
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      image:
        tag: "1.3.0-PR1235-0de45d2-9360578046"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
      swagger:
        enabled: false
    explorerRewardsApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.3.0"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.9.0-PR128"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      emailFrom: "admin@beta.explorer.cardano.org"
      keycloakServerUrl: "https://keycloak.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.3.0-PR3663-9136b9c-9711975199"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/api/v1"
      # temporary
      reactAppAdaHandleApi: "https://adahandle-resolver.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/api/v1"
      reactAppApiUrl: "https://api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/api/v1"
      reactAppWsUrl: "wss://api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/ws"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: false
      replicas: 1
      image:
        tag: "1.3.1-PR491-2533985-9838561456"
      ledgerSyncFlywayEnable: "true"
      explorerFlywayEnable: "true"
      aggAnalyticJobEnabled: "true"
      tokenInfoJobEnabled: "true"
      tokenInfoBatchSize: 1000
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://beta.explorer.cardano.org
      webOrigin: https://beta.explorer.cardano.org
      redirectUri: https://beta.explorer.cardano.org/*
      forwardEventUrl: https://beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    ingress:
      enabled: true
      additionalDomains:
        - adahandle-resolver.pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org
        - adahandle-resolver.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
        - adahandle-resolver.mainnet.global.beta.explorer.cardano.org
    springProfiles: mainnet,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
