stage: stg

network: mainnet

domain: stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    enabled: false
  redis:
    enabled: true
  kafka:
    dbSize: 750Gi

cf-explorer:
  values:
    crawler:
      enabled: true
      image:
        tag: "0.2.7"
      redis:
        mode: standalone
    consumer:
      enabled: true
      image:
        tag: "0.3.2-SNAPSHOT"
    explorerApi:
      image:
        tag: "0.3.13"
      redis:
        mode: standalone
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.2-SNAPSHOT"
    explorerAuthentication:
      replicas: 1
      image:
        tag: "0.1.4-SNAPSHOT"
      redis:
        mode: standalone
    explorerFrontEnd:
      image:
        tag: "0.4.0"
    consumerSchedules:
      image:
        tag: "0.2.4-SNAPSHOT"
      redis:
        mode: standalone

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org
