stage: stg

network: preprod

domain: stg.cf-explorer-preprod.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: false

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: stg.cf-explorer-preprod.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: stg.cf-explorer-preprod.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: stg.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org
    crawler:
      enabled: true
      image:
        tag: "0.2.12"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      redis:
        standalone:
          host: master.stg-cf-explorer-preprod.szs8qo.euw1.cache.amazonaws.com
          useSsl: "true"
    consumer:
      enabled: true
      image:
        tag: "0.3.12"
      redis:
        standalone:
          host: master.stg-cf-explorer-preprod.szs8qo.euw1.cache.amazonaws.com
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
    explorerApi:
      enabled: true
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      image:
        tag: "0.3.26"
      redis:
        standalone:
          host: master.stg-cf-explorer-preprod.szs8qo.euw1.cache.amazonaws.com
          useSsl: "true"
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.7-SNAPSHOT"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.1.11"
      redis:
        standalone:
          host: master.stg-cf-explorer-preprod.szs8qo.euw1.cache.amazonaws.com
          useSsl: "true"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.4.13"
      reactAppPreProdAppUrl: "https://stg.cf-explorer-preprod.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.stg.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.2.10"
      redis:
        standalone:
          host: master.stg-cf-explorer-preprod.szs8qo.euw1.cache.amazonaws.com
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.stg.cf-explorer-preprod.metadata.dev.cf-deployments.org
