stage: pro

network: preprod

domain: preprod.beta.explorer.cardano.org

cf-explorer-infra:
  enabled: true
  postgresql:
    enabled: true
    dbSize: 450Gi
  kafka:
    dbSize: 20Gi

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop"
    useLocalCardanoNode: false
    localCardanoNode:
      enabled: false
      volumeSize: 20Gi
      network: "preprod"
    indexer:
      enabled: true
      replicaCount: 1
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
        tag: "0.0.42-SNAPSHOT-e2a0a39-9790569873"
      postgres:
        secretName: postgres-secrets-local
    aggregation:
      enabled: true
      replicaCount: 1
      image:
        repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync-aggregation"
        tag: "0.0.42-SNAPSHOT-e2a0a39-9790569873"
      postgres:
        secretName: postgres-secrets-local
        dbSchema: preprod
      store:
        account:
          history_cleanup_enabled: "false"
        executor:
          enable_parallel_processing: "true"

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: preprod.beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-preprod.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-preprod.us-east-1.beta.explorer.cardano.org
    explorerApi:
      enabled: true
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      image:
        tag: "1.3.0-PR1295-78273da-9962749390"
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
      swagger:
        enabled: false
    explorerRewardsApi:
      enabled: true
      image:
        tag: "1.3.0"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.9.0-PR128"
      emailFrom: "admin@beta.explorer.cardano.org"
      keycloakServerUrl: "https://keycloak.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.3.0-PR3663-42ef61e-9970750131"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org/api/v1"
      # temporary
      #reactAppApiUrl: "https://api.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org/api/v1"
      #reactAppWsUrl: "wss://api.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org/ws"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: true
      replicas: 0
      image:
        tag: "1.3.1-PR491-9e7e959-9975832901"
      ledgerSyncFlywayEnable: "true"
      explorerFlywayEnable: "true"
      aggAnalyticJobEnabled: "true"
      tokenInfoJobEnabled: "true"
      tokenInfoBatchSize: 1000
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://preprod.beta.explorer.cardano.org
      webOrigin: https://preprod.beta.explorer.cardano.org
      redirectUri: https://preprod.beta.explorer.cardano.org/*
      forwardEventUrl: https://preprod.beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    ingress:
      enabled: true
      additionalDomains:
        - adahandle-resolver.pro.cf-explorer-preprod.us-east-1.beta.explorer.cardano.org
        - adahandle-resolver.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org
        - adahandle-resolver.preprod.global.beta.explorer.cardano.org
    springProfiles: preprod,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-preprod.eu-west-1.beta.explorer.cardano.org
