stage: dev

network: mainnet

domain: dev.ggargiulo-clusters.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    dbSize: 750Gi
  kafka:
    dbSize: 750Gi

cf-explorer:
  enabled: false
  values:
    crawler:
      enabled: true
      image:
        tag: "0.2.7"
    consumer:
      enabled: true
      image:
        tag: "0.3.2"
    explorerApi:
      enabled: false
      image:
        tag: "0.3.14"
    explorerRewardsApi:
      enabled: false
      image:
        tag: "0.1.2"
    explorerAuthentication:
      enabled: false
      replicas: 1
      image:
        tag: "0.1.4"
    explorerFrontEnd:
      enabled: false
      image:
        tag: "0.4.1"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.2.4-SNAPSHOT"

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.dev.ggargiulo-clusters.eu-west-1.metadata.dev.cf-deployments.org
