stage: dev

network: mainnet

domain: dev.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    dbSize: 1500Gi
  kafka:
    dbSize: 750Gi

cf-explorer:
  enabled: true
  values:
    crawler:
      enabled: true
      image:
        tag: "0.2.7"
    consumer:
      enabled: true
      image:
        tag: "0.3.4"
    explorerApi:
      image:
        tag: "0.3.14"
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.2"
    explorerAuthentication:
      replicas: 1
      image:
        tag: "0.1.4"
    explorerFrontEnd:
      image:
        tag: "0.4.1"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.2.4-SNAPSHOT"

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.dev.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
