stage: stg

network: mainnet

domain: stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    enabled: false
  redis:
    enabled: false
  kafka:
    enabled: false

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: stg.cf-explorer-mainnet.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: stg.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
    crawler:
      enabled: true
      image:
        tag: "0.2.9"
      redis:
        mode: standalone
    consumer:
      enabled: true
      #springProfiles: aws,redis-standalone
      image:
        tag: "0.3.6"
      springProfiles: aws
      redis:
        mode: standalone
    explorerApi:
      s3:
        bucketName: stg-cf-explorer-mainnet-reports
        region: eu-west-1
        endpoint: https://s3-eu-west-1.amazonaws.com
        secret:
          name: infra-secrets
          accessKeyKey: S3_ACCESS_KEY
          secretKeyKey: S3_SECRET_KEY
      image:
        tag: "0.3.20"
      redis:
        mode: standalone
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.4"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.1.6"
      redis:
        mode: standalone
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.4.6"
      reactAppPreProdAppUrl: "https://stg.cf-explorer-preprod.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.stg.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    consumerSchedules:
      enabled: true
      s3:
        bucketName: stg-cf-explorer-mainnet-reports
        region: eu-west-1
        endpoint: https://s3-eu-west-1.amazonaws.com
        secret:
          name: infra-secrets
          accessKeyKey: S3_ACCESS_KEY
          secretKeyKey: S3_SECRET_KEY
      image:
        tag: "0.2.7"
      redis:
        mode: standalone

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org
