stage: pro

network: mainnet

domain: beta.explorer.cardano.org

cf-explorer-infra:
  enabled: false

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-mainnet.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-mainnet.us-east-1.beta.explorer.cardano.org
    crawler:
      enabled: true
      image:
        tag: "0.2.12"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
    consumer:
      enabled: true
      image:
        tag: "0.3.14"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
    explorerApi:
      enabled: true
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      image:
        tag: "0.3.31"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.7-SNAPSHOT"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.1.13"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      emailFrom: "admin@beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "0.4.22"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org/api/v1"

    consumerSchedules:
      enabled: true
      image:
        tag: "0.2.12"
      redis:
        mode: managed-standalone
        standalone:
          useSsl: "true"
      kafka:
        useSsl: "true"
        bootstrapServersSecret:
          name: infra-secrets
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-mainnet.eu-west-1.beta.explorer.cardano.org
