stage: stg

network: preview

domain: stg.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  postgresql:
    dbSize: 450Gi
    nodeSelector:
      node.kubernetes.io/role: postgres
    tolerations:
      - key: role
        value: postgres
        operator: Equal
        effect: PreferNoSchedule

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop-1_7_0"
    localCardanoNode:
      enabled: true
      volumeSize: 20Gi
      network: "preview"
    indexer:
      enabled: true
      replicaCount: 1
      image:
        tag: "0.1.0"
      postgres:
        secretName: postgres-secrets-local
    aggregation:
      enabled: true
      replicaCount: 1
      image:
        tag: "0.1.0"
      db:
        maximum_pool_size: 60
      postgres:
        secretName: postgres-secrets-local
        dbSchema: preview
      store:
        account:
          history_cleanup_enabled: "false"
#        executor:
#          enable_parallel_processing: "true"
#          use_virtual_thread_for_batch_processing: "true"
#          use_virtual_thread_for_event_processing: "true"

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: stg.cf-explorer-preview.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: stg.cf-explorer-preview.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: stg.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org
    explorerApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.7.0-PR1349-6a9dcdb-10594521919"
      tokenLogoEndpoint: https://stg-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    explorerRewardsApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.5.0-593f9b1-10371126638"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "1.4.0-1e3e78d-10371096098"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.7.0-main-7a4d7e5-10371257901"
      reactAppSanchonetAppUrl: "https://stg.cf-explorer-sanchonet.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppPreProdAppUrl: "https://stg.cf-explorer-preprod.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://stg.cf-explorer-mainnet.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.stg.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: true
      replicas: 1
      image:
        tag: "1.7.0-PR536-7f029a9-10645800258"
      tokenLogoEndpoint: https://stg-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.stg.cf-explorer-preview.global.metadata.dev.cf-deployments.org
      frontendDomainPublicUrl: https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org
      webOrigin: https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org
      redirectUri: https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org/*
      forwardEventUrl: https://stg.cf-explorer-preview.metadata.dev.cf-deployments.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    springProfiles: preview,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.stg.cf-explorer-preview.metadata.dev.cf-deployments.org
