stage: dev

network: preprod

domain: dev.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: false
  postgresql:
    dbSize: 150Gi
  kafka:
    dbSize: 20Gi

cf-explorer:
  enabled: false
  values:
    crawler:
      enabled: true
      image:
        tag: "0.2.7"
    consumer:
      enabled: false
      image:
        tag: "0.3.2-SNAPSHOT"
    explorerApi:
      image:
        tag: "0.3.13"
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.2-SNAPSHOT"
    explorerAuthentication:
      replicas: 1
      image:
        tag: "0.1.4-SNAPSHOT"
    explorerFrontEnd:
      image:
        tag: "0.4.0"
    consumerSchedules:
      enabled: false
      image:
        tag: "0.2.4-SNAPSHOT"

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.dev.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org 
