git:
  targetRevision: main

stage: pro

network: preview

domain: preview.beta.explorer.cardano.org

cf-explorer-infra:
  enabled: true
  postgresql:
    enabled: false
  kafka:
    dbSize: 20Gi

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "chore/add-cardano-node-to-helm-chart"
    replicaCount: 1
    image:
      repository: "pro.registry.gitlab.metadata.dev.cf-deployments.org/base-infrastructure/docker-registry/cf-ledger-sync"
      tag: "0d6d20f-8246831004"
    ingress:
      enabled: false
    useLocalCardanoNode: true
    localCardanoNode:
      enabled: true
      network: "preview"
      image:
        repository: ghcr.io/intersectmbo/cardano-node
        tag: 8.9.0

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: preview.beta.explorer.cardano.org
      - name: global-lb
        domain: pro.cf-explorer-preview.global.beta.explorer.cardano.org
      - name: eu-west-1-lb
        domain: pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org
      - name: us-east-1-lb
        domain: pro.cf-explorer-preview.us-east-1.beta.explorer.cardano.org
    crawler:
      enabled: false
    consumer:
      enabled: false
    explorerApi:
      enabled: true
      image:
        tag: "0.8.0-PR1038-f74b963-8135114438"
      postgres:
        secret:
          hostKey: POSTGRES_READ_ONLY_HOST
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    explorerRewardsApi:
      enabled: true
      image:
        tag: "0.1.8-SNAPSHOT-PR93-1299c79-7912678888"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.5.0-SNAPSHOT-sanchonet-PR123"
      emailFrom: "admin@beta.explorer.cardano.org"
      keycloakServerUrl: "https://keycloak.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.0.0-PR3105-cee63ea-8321247451"
      reactAppSanchonetAppUrl: "https://sanchonet.beta.explorer.cardano.org"
      reactAppPreProdAppUrl: "https://preprod.beta.explorer.cardano.org"
      reactAppPreviewAppUrl:  "https://preview.beta.explorer.cardano.org"
      reactAppMainnetAppUrl: "https://beta.explorer.cardano.org"
      reactAppAuthUrl: "https://auth-api.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/api/v1"
      # temporary
      reactAppApiUrl: "https://api.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/api/v1"
      reactAppWsUrl: "wss://api.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org/ws"
    consumerSchedules:
      enabled: true
      image:
        tag: "0.9.0-PR318-4932450-8235150499"
      tokenLogoEndpoint: https://pro-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org
      frontendDomainPublicUrl: https://preview.beta.explorer.cardano.org
      webOrigin: https://preview.beta.explorer.cardano.org
      redirectUri: https://preview.beta.explorer.cardano.org/*
      forwardEventUrl: https://preview.beta.explorer.cardano.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    springProfiles: preview,postgres
    image:
      tag: "0.1.3"

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.pro.cf-explorer-preview.eu-west-1.beta.explorer.cardano.org
