stage: uat

network: mainnet

domain: uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org

cf-explorer-infra:
  enabled: true
  redis:
    values:
      master:
        persistence:
          size: 20Gi
      diagnosticMode:
        enabled: false
  postgresql:
    enabled: true
    dbSize: 4500Gi
    nodeSelector:
      node.kubernetes.io/role: resync-pg
    tolerations:
      - key: role
        value: resync-pg
        operator: Equal
        effect: PreferNoSchedule

postgres:
  operator:
    enabled: true

cf-ledger-sync:
  enabled: true
  values:
    git:
      targetRevision: "infra-develop-1_7_0"
    localCardanoNode:
      enabled: true
      volumeSize: 200Gi
      network: "mainnet"
    indexer:
      enabled: true
      replicaCount: 0
      image:
        tag: "0.1.0"
#    blocks:
#      batchSize: "10"
    aggregation:
      enabled: true
      replicaCount: 0
      image:
        tag: "0.1.0"
      db:
        maximum_pool_size: 60
      postgres:
        dbSchema: mainnet
      store:
        account:
          history_cleanup_enabled: "false"
        executor:
          enable_parallel_processing: "true"
          use_virtual_thread_for_batch_processing: "true"
          use_virtual_thread_for_event_processing: "true"

cf-explorer:
  enabled: true
  values:
    ingressDomains:
      - name: cloudfront
        domain: uat.cf-explorer-mainnet.metadata.dev.cf-deployments.org
      - name: global-lb
        domain: uat.cf-explorer-mainnet.global.metadata.dev.cf-deployments.org
      - name: eu-west-1-lb
        domain: uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
    explorerApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.3.0-PR1310-40025e3-10277352293"
      tokenLogoEndpoint: https://uat-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    explorerRewardsApi:
      enabled: true
      replicas: 1
      image:
        tag: "1.3.0-PR103-0cd6aab-9754219477"
    explorerAuthentication:
      enabled: true
      replicas: 1
      image:
        tag: "0.9.0-PR132-394f1ba-9743398271"
    explorerFrontEnd:
      enabled: true
      image:
        tag: "1.6.0-PR-f71b692-10285504534"
      reactAppSanchonetAppUrl: "https://uat.cf-explorer-sanchonet.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppPreProdAppUrl: "https://uat.cf-explorer-preprod.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppPreviewAppUrl: "https://uat.cf-explorer-preview.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppMainnetAppUrl: "https://uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org"
      reactAppAuthUrl: "https://auth-api.uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org/api/v1"
    crawler:
      enabled: false
    consumer:
      enabled: false
    consumerSchedules:
      enabled: true
      replicas: 0
      image:
        tag: "1.3.0-PR517-8d4bff0-10264448294"
      tokenLogoEndpoint: https://uat-cf-explorer-token-logos.s3.eu-west-1.amazonaws.com/
    keycloak:
      enabled: true
      image:
        tag: 0.1.15-SNAPSHOT
      setupImage:
        tag: 0.1.15-SNAPSHOT
      hostname: keycloak.uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
      frontendDomainPublicUrl: https://uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
      webOrigin: https://uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
      redirectUri: https://uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org/*
      forwardEventUrl: https://uat.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org/api/v1/user/role-mapping

# Ada Handle Parameters
adahandle-resolver:
  enabled: true
  values:
    ingress:
      enabled: true
      additionalDomains:
        - adahandle-resolver.uat.cf-explorer-mainnet.metadata.dev.cf-deployments.org
        - adahandle-resolver.uat.cf-explorer-mainnet.global.metadata.dev.cf-deployments.org
    springProfiles: mainnet,postgres
    image:
      tag: "0.1.3"

kube-prometheus-stack:
  enabled: true
  version: 58.0.0

argo-cd:
  server:
    ingress:
      hosts:
        - argocd.dev.cf-explorer-mainnet.eu-west-1.metadata.dev.cf-deployments.org
