apiVersion: v1
kind: Service
metadata:
  name: {{ include "cf-product-tracing-aggregator.fullname" . }}
  labels:
    {{- include "cf-product-tracing-aggregator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cf-product-tracing-aggregator.selectorLabels" . | nindent 4 }}
