---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: explorer-db-dump
spec:
  schedule: "0 0 31 2 *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: explorer-db-dump
              image: "{{ $.Values.annoyJobs.image.repository }}:{{ $.Values.annoyJobs.image.tag }}"
              env:
                - name: JAVA_OPTS
                  value: "-Dconfig.resource=application.prod.conf"
                - name: SCALEWAY_S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: polygraph-s3-secret
                      key: POLYGRAPH_S3_ACCESS_KEY
                - name: SCALEWAY_S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: polygraph-s3-secret
                      key: POLYGRAPH_S3_SECRET_KEY
                - name: PGHOST
                  value: polygraph-postgres-mainnet-postgresql
                - name: PGPORT
                  value: "5432"
                - name: PGDATABASE
                  value: polygraph
                - name: PGUSER
                  value: polygraph
                - name: PGPASSWORD
                  value: polygraph
              resources:
                limits:
                  memory: "4Gi"
                  cpu: 1
                requests:
                  memory: "4Gi"
                  cpu: 1
          restartPolicy: OnFailure
