{
 "title": "cardano-node (stakepool overview)",
 "description": "k8s-oriented cardano-node dashboard for metrics and logs built with 💜 by La RepsistancE: https://twitter.com/repsistance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "cardano-mn, cardano-tn, cardano-tn2"
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(cardano_node_metrics_nodeStartTime_int{namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cardano-node general metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cardano-node/uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - cardano_node_metrics_nodeStartTime_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Epoch details",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Slot in Epoch"
    },
    {
     "expr": "432000 - cardano_node_metrics_slotInEpoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Slot in Epoch left"
    }
   ]
  },
  {
   "title": "Time to end of Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "432000 - cardano_node_metrics_slotInEpoch_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/process-memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Mem_resident_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/block-sync-speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}[150s])*60",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/chain-density",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{namespace=~\"$namespace\", pod=~\"$pod\"} * 100",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/slot-height",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/block-cdf-propagation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "One Second"
    },
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfThree{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Three"
    },
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfFive{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Five"
    }
   ]
  },
  {
   "title": "cardano-node/block-delay",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_s",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/block-height",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/late-blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_lateblocks{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Num late blocks ( > 5s )"
    }
   ]
  },
  {
   "title": "cardano-node/connected-peers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/p2p",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_cold{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Cold"
    },
    {
     "expr": "cardano_node_metrics_peerSelection_hot{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Hot"
    },
    {
     "expr": "cardano_node_metrics_peerSelection_warm{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Warm"
    }
   ]
  },
  {
   "title": "cardano-node/p2p-governor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_inboundGovernor_cold{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Cold"
    },
    {
     "expr": "cardano_node_metrics_inboundGovernor_hot{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Hot"
    },
    {
     "expr": "cardano_node_metrics_inboundGovernor_idle{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "cardano_node_metrics_inboundGovernor_warm{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "Warm"
    }
   ]
  },
  {
   "title": "Key Evolving Signature (KES) Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current KES Period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Current KES Period"
    }
   ]
  },
  {
   "title": "op Cert Start KES period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_operationalCertificateStartKESPeriod_int{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "op Cert Expiry KES period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "op Cert Remaining KES period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "KES Expiration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_remainingKESPeriods_int{namespace=\"$namespace\", pod=\"$pod\"} * 129600"
    }
   ]
  },
  {
   "title": "cardano-node leader metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cardano-node/pool-performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int{namespace=~\"$namespace\", pod=~\"$pod\"} / cardano_node_metrics_Forge_node_is_leader_int{namespace=~\"$namespace\", pod=~\"$pod\"} * 100",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/blocks-assigned",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/forged-blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/adopted-blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_adopted_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/forge-about-to-lead",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forge_about_to_lead_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/missed-slot",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/could-not-forge (broken?)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_could_not_forge_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "cardano-node/not-adopted-blocks (broken?)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_didnt_adopt_int{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{namespace}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Resource metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage (cores)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=\"$pod\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PVC free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}