{
 "title": "Crawler Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Block Number",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "crawler_current_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Block ERA",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "crawler_current_era", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Sync Percent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_network_sync_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of rollbacks",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "crawler_count_rollback_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ERA processing time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(crawler_block_processing_timer_seconds_sum) by (era)",
     "legendFormat": "{{era}}"
    }
   ]
  },
  {
   "title": "AVG processing time each block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(crawler_block_processing_timer_seconds_sum)/sum(crawler_block_processing_timer_seconds_count)",
     "legendFormat": "AVG processing time each block"
    }
   ]
  },
  {
   "title": "Number of block processed per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(crawler_block_processing_timer_seconds_count[1m]))*60",
     "legendFormat": "Number of block processed per minute"
    }
   ]
  },
  {
   "title": "Epoch processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum ( rate( crawler_block_processing_timer_seconds_count[1m] ) ) by (epoch)",
     "legendFormat": "Epoch {{epoch}}"
    }
   ]
  }
 ]
}